### PR TITLE
Create swagger-generator-cli-1.1.14-SNAPSHOT-executable.jar

### PR DESCRIPTION
**Pull request by arthurMll**
New yang2oas 1.1.14-SNAPSHOT cli executable file.

### CODE REVIEW

**Comment by pedrofsamaral** [comment]
Not sure if you consider it relevant for the case but since it will be commit in TAPI repo, 

- I suggest changing the name of the jar file since "-SNAPSHOT" is a keyword in MAVEN that may be confusing; 
- in addition, it may be valuable to reference the exact source files or point in time it was generated (https://github.com/bartoszm/yang2swagger/tree/541e0a1dd5a0accdb7736c7c8da7d185877f6075). I mean that if the source files change in the (yang2swagger) master repo for some reason we may come up with a different -SNAPSHOT jar file and it may be hard to identify which version we are using. 

We may use something like "swagger-generator-cli-1.1.14-DRAFT-541e0a1" being 541e0a1 the latest commit on master at this point. In the file comments we may include the direct link for the commit (https://github.com/bartoszm/yang2swagger/tree/541e0a1dd5a0accdb7736c7c8da7d185877f6075).

**Comment by amazzini** [comment]
The version 14 apparently works, no error found in the log files.

**Review by karthik-sethuraman — APPROVED** [review]
i have not tested, but also haven't received response from @bartoszm

**Review by amazzini — APPROVED** [review]
Used this version for https://github.com/OpenNetworkingFoundation/TAPI/pull/486
generation of OAS.

**Pull request merged**
