### PR TITLE
Adding Streaming to V2.1

### PR DESCRIPTION
**Pull request by nigel-r-davis**
This is fully aligned with streaming in the develop branch.

### CODE REVIEW

**Review by arthurMll — CHANGES_REQUESTED** [review]
It seems there are a couple of leafrefs which are still not correct.

Line 607:
```       leaf available-stream {
            type leafref {
                path '/tapi-common:context/tapi-streaming:available-stream/tapi-streaming:connection-address';
            }
            config false;
            description "none";
```
should be:
```       leaf available-stream {
            type leafref {
                path '/tapi-common:context/tapi-streaming:stream-context/available-stream/connection-address';
            }
            config false;
            description "none";
```
And at line 651:
```       leaf stream-connection-type {
            type leafref {
                path '/tapi-common:context/tapi-streaming:supported-stream-type/tapi-streaming:stream-type-id';
            }
            config false;
            description "Identifies the type of stream that is available for connection.";
        }
```
It should be:
```       leaf stream-connection-type {
            type leafref {
                path '/tapi-common:context/tapi-streaming:stream-context/supported-stream-type/stream-type-id';
            }
            config false;
            description "Identifies the type of stream that is available for connection.";
        }
```

**Comment by nigel-r-davis** [comment]
I agree that we need to fix this. This seems to be an issue with the UML-Yang tooling as far as I can see at this point. If so it will need a simple manual fix as identified in the comments.

**Comment by nigel-r-davis** [comment]
Sorry for the tangle of apparent changes, I polluted the branch then had to revert and re-add to put it back together again. The only real change here is the final one (5c4739a - leafref correction).

**Review by arthurMll — APPROVED** [review]
YANG tree is correctly generated now.

**Pull request merged**
